[core]
reloadable = true
order = 0

[package]
version = "0.0.5-beta"
category = "Other"
feature = false
app = false
title = "OpenXR (compact binding)"
description = "OpenXR compact binding for Omniverse"
authors = ["Toni-SM"]
repository = "https://github.com/Toni-SM/semu.xr.openxr"
keywords = ["OpenXR", "XR", "VR", "AR"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[package.target]
config = ["release"]
platform = ["linux-x86_64"]
python = ["py37", "cp37"]

[dependencies]
"omni.ui" = {}
"omni.physx" = {}
"omni.kit.uiapp" = {}
"omni.kit.pipapi" = {}
"omni.syntheticdata" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.viewport" = {}

[[python.module]]
name = "semu.xr.openxr"

[[python.module]]
name = "semu.xr.openxr_ui"

[[python.module]]
name = "semu.xr.openxr.tests"

[python.pipapi]
requirements = ["opencv-python"]
use_online_index = true

[settings]
exts."semu.xr.openxr".disable_openxr = false
